### ISSUE TITLE
Puppeteer

### ISSUE THREAD

**Issue by w0otness** [hayd/deno-lambda#142]
I've been trying to get puppeteer running in this Dockerfile.
```
FROM hayd/deno-lambda:1.13.2
ENV PUPPETEER_PRODUCT=chrome
RUN deno run -A --unstable https://deno.land/x/puppeteer@9.0.1/install.ts
COPY hello.ts .
RUN deno cache --unstable hello.ts
CMD ["hello.handler"]
```
and hello.ts:
```
import {
  APIGatewayProxyEventV2,
  APIGatewayProxyResultV2,
  Context,
} from "https://deno.land/x/lambda/mod.ts";
import puppeteer from "https://deno.land/x/puppeteer@9.0.1/mod.ts";

export async function handler(
  event: APIGatewayProxyEventV2,
  context: Context,
): Promise<APIGatewayProxyResultV2> {
  console.log('start');
  const browser = await puppeteer.launch({
    headless: true,
    args: [
      "--no-sandbox",
      "--disable-dev-shm-usage",
    ]
  });
  const page = (await browser.pages())[0];
  await browser.close();
  console.log('finish');
  return {
    statusCode: 200,
    headers: { "content-type": "text/html;charset=utf8" },
    body: `Welcome to deno ${Deno.version.deno} 🦕`,
  };
}
```

Gets:
Error: Could not find browser revision 869685. Run "PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@9.0.1/install.ts" to download a supported browser binary.

It seems that the `RUN deno run -A --unstable https://deno.land/x/puppeteer@9.0.1/install.ts` doesn't persist chrome into the image, as `RUN chrome` after it doesn't work.

I've also tried to install chrome by `RUN curl https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm -o ./google-chrome-stable_current_x86_64.rpm && yum install ./google-chrome-stable_current_x86_64.rpm -y && ln -s /usr/bin/google-chrome-stable /usr/bin/chrome` where `RUN chrome` now works but still get the same error.

**Comment by hayd** [comment]
I recommend bashing into the docker container to debug:
```
❱ docker run -p 9000:8080 --platform linux/amd64 --init -it --entrypoint="bash" -t chrome
bash-4.2# chrome
bash: chrome: command not found
bash-4.2# PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@9.0.1/install.ts
Already downloaded at /var/task/.deno_dir/deno_puppeteer/chromium/linux-869685/chrome-linux/chrome
bash-4.2# chrome
bash: chrome: command not found
bash-4.2# /var/task/.deno_dir/deno_puppeteer/chromium/linux-869685/chrome-linux/chrome
/var/task/.deno_dir/deno_puppeteer/chromium/linux-869685/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
```
So it looks like it does persist (chrome was downloaded in the install step) but is some kind of PATH issue? Also chrome might require installing some additional libraries.

When I comment out the lambda boilerplate and try to run the block inside the function I get:
```
bash-4.2# deno run -A --unstable hello1.ts
start
error: Uncaught (in promise) BadResource: Bad resource ID
    const result = await reader.read(inspectArr);
                   ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async read (deno:runtime/js/12_io.js:107:19)
    at async readDelim (https://deno.land/std@0.93.0/io/bufio.ts:652:20)
    at async readStringDelim (https://deno.land/std@0.93.0/io/bufio.ts:702:20)
    at async readLines (https://deno.land/std@0.93.0/io/bufio.ts:711:18)
    at async waitForWSEndpoint (https://deno.land/x/puppeteer@9.0.1/src/deno/BrowserRunner.ts:167:20)
    at async BrowserRunner.setupConnection (https://deno.land/x/puppeteer@9.0.1/src/deno/BrowserRunner.ts:145:31)
    at async ChromeLauncher.launch (https://deno.land/x/puppeteer@9.0.1/src/deno/Launcher.ts:114:26)
    at async file:///var/task/hello1.ts:4:19
```
😬

**Comment by w0otness** [comment]
I got it running using:
```
FROM hayd/deno-lambda:1.13.2
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum install -y chromium
RUN deno run -A --unstable https://deno.land/x/puppeteer@9.0.1/install.ts
COPY hello.ts .
RUN deno cache --unstable hello.ts
CMD ["hello.handler"]
```
Needed the additional libraries from EPEL. Thanks!
